# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promener < Formula
  desc "Generates structured Prometheus metrics code with named parameters and interactive HTML documentation from YAML specifications"
  homepage "https://github.com/jycamier/promener"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jycamier/promener/releases/download/v1.1.0/promener_Darwin_x86_64.tar.gz"
      sha256 "a0f9787d23206fcd7fcd0d45ee033cf4b8e72519fca3fa7438c9f5a49f6e525a"

      def install
        bin.install "promener"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jycamier/promener/releases/download/v1.1.0/promener_Darwin_arm64.tar.gz"
      sha256 "9de9da7015d9cc5f3ed95490544143b70702eab5a775d0bcdbcd32f0e0550e92"

      def install
        bin.install "promener"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jycamier/promener/releases/download/v1.1.0/promener_Linux_x86_64.tar.gz"
      sha256 "8cb2e946693697b22458b33dd4f456ee4f7458de1b6c8cdf6e96561147d09283"
      def install
        bin.install "promener"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jycamier/promener/releases/download/v1.1.0/promener_Linux_arm64.tar.gz"
      sha256 "a8edb34f2dd4158a3fee8f2d0a9dd69fe0bd80c431a923728fcc94cbce3af378"
      def install
        bin.install "promener"
      end
    end
  end

  test do
    system "#{bin}/promener version"
  end
end
