# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrapper < Formula
  desc "Configuration profile manager for any CLI binary"
  homepage "https://github.com/jycamier/wrapper"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jycamier/wrapper/releases/download/v1.1.0/wrapper_Darwin_x86_64.tar.gz"
      sha256 "55609568726e4a41a583463e8539112d7839e1d5bf62ce886a0a0255f4a2cac9"

      def install
        bin.install "wrapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jycamier/wrapper/releases/download/v1.1.0/wrapper_Darwin_arm64.tar.gz"
      sha256 "83f729612deb0477b51b1138602301a2772e4be870d9f57fcd223c22d6a797ae"

      def install
        bin.install "wrapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jycamier/wrapper/releases/download/v1.1.0/wrapper_Linux_x86_64.tar.gz"
      sha256 "e23ef1414986474f3cc367dfa4261fc3e017b1f46287a1c25d98a8386ce22de9"
      def install
        bin.install "wrapper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jycamier/wrapper/releases/download/v1.1.0/wrapper_Linux_armv6.tar.gz"
      sha256 "a098ed2d6c13c77875166d1e15ac770383929c07f17d398547036565dc201be0"
      def install
        bin.install "wrapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jycamier/wrapper/releases/download/v1.1.0/wrapper_Linux_arm64.tar.gz"
      sha256 "077cfbee2c5b608a04db89b5d4da90f3cc0689fd28a925926a93df7145ffcf1f"
      def install
        bin.install "wrapper"
      end
    end
  end

  test do
    system "#{bin}/wrapper version"
  end
end
