# This file was generated by GoReleaser. DO NOT EDIT.
cask "promener" do
  name "promener"
  desc "Generates structured Prometheus metrics code with named parameters and interactive HTML documentation from YAML specifications"
  homepage "https://github.com/jycamier/promener"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promener"

  on_macos do
    on_intel do
      url "https://github.com/jycamier/promener/releases/download/v#{version}/promener_Darwin_x86_64.tar.gz"
      sha256 "526f541689f0996f03a4ee1eb9672669d2a56098df5202b742d717f612b02a44"
    end
    on_arm do
      url "https://github.com/jycamier/promener/releases/download/v#{version}/promener_Darwin_arm64.tar.gz"
      sha256 "2ee18ddd66a26e70ab36937206e50e8a3a9e85a68f792dea70e8d28aa59848b6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jycamier/promener/releases/download/v#{version}/promener_Linux_x86_64.tar.gz"
      sha256 "2157c9396440e5f372ef0151cb1d9c1f31031f5c9d16391efb9d81a0ac2f09ec"
    end
    on_arm do
      url "https://github.com/jycamier/promener/releases/download/v#{version}/promener_Linux_arm64.tar.gz"
      sha256 "d672f22432df7318807a89695f4553e6843d71b2b03ca6db12dd5004f4d266ff"
    end
  end

  # No zap stanza required
end
